=== ERRAFI-IMRANE/XML-TPS/TPS/TP2/Excercice-2.dtd
<!ELEMENT Hopital (Nom,Medecin+)>
<!ELEMENT Medecin (Nom,Prenom,Specialite?,Service?,Phone*,Email*,Date,Adresse,Photo)>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Specialite (#PCDATA)>
<!ELEMENT Service (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Date EMPTY>
<!ELEMENT Adresse (Rue,Numero,codePostal,Ville)>
<!ELEMENT Rue (#PCDATA)>
<!ELEMENT Numero (#PCDATA)>
<!ELEMENT codePostal (#PCDATA)>
<!ELEMENT Ville (#PCDATA)>
<!ELEMENT Photo EMPTY>

<!ATTLIST Hopital idDirecteur IDREF #REQUIRED>
<!ATTLIST Medecin id ID #REQUIRED>
<!ATTLIST Phone type (GSM | fixe) "GSM">
<!ATTLIST Email type (personnel | professionnel) "personnel">
<!ATTLIST Photo scr CDATA #REQUIRED type (PNG | JPG) "PNG">
<!ATTLIST Medecin grade (interne | resident | specialite | professeur) #REQUIRED>
<!ATTLIST Date Jour CDATA #REQUIRED>
<!ATTLIST Date Month CDATA #REQUIRED>
<!ATTLIST Date Annee CDATA #REQUIRED>

=== ERRAFI-IMRANE/XML-TPS/TPS/TP2/Exercice-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hopital SYSTEM "Excercice-2.dtd">
<Hopital idDirecteur="M001">
    <Nom>CHU Safi</Nom>
    <Medecin id="M001" grade="interne">
        <Nom>Errafi</Nom>
        <Prenom>Imrane</Prenom>
        <Specialite>Cardio</Specialite>
        <Date Jour="09" Month="06" Annee="2005"/>
        <Adresse>
            <Rue>Sidi Rached Lalla haffsa</Rue>
            <Numero>8</Numero>
            <codePostal>51300</codePostal>
            <Ville>Azrou</Ville>
        </Adresse>
        <Photo scr=""/>
    </Medecin>
    <Medecin id="M002" grade="resident">
        <Nom>Errafi</Nom>
        <Prenom>Imrane</Prenom>
        <Specialite>Cardio</Specialite>
        <Date Jour="09" Month="06" Annee="2005"/>
        <Adresse>
            <Rue>Sidi Rached Lalla haffsa</Rue>
            <Numero>8</Numero>
            <codePostal>51300</codePostal>
            <Ville>Azrou</Ville>
        </Adresse>
        <Photo scr=""/>
    </Medecin>
    <Medecin id="M003" grade="specialite">
        <Nom>Errafi</Nom>
        <Prenom>Imrane</Prenom>
        <Specialite>Cardio</Specialite>
        <Date Jour="09" Month="06" Annee="2005"/>
        <Adresse>
            <Rue>Sidi Rached Lalla haffsa</Rue>
            <Numero>8</Numero>
            <codePostal>51300</codePostal>
            <Ville>Azrou</Ville>
        </Adresse>
        <Photo scr=""/>
    </Medecin>
</Hopital>
