=== ERRAFI-IMRANE/XML-TPS/TPS/TP2/Exercice-1.dtd
<!ENTITY % unique "ID #REQUIRED">
<!ELEMENT Publications (Publication+)>
<!ELEMENT Publication (Titre, Auteur+, Date, Type, Resume?)>
<!ELEMENT Titre (#PCDATA)>
<!ELEMENT Auteur (Nom, Prenom, Affiliation)>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Affiliation (#PCDATA)>
<!ELEMENT Date EMPTY>
<!ELEMENT Resume (#PCDATA|MotClef)*>
<!ELEMENT MotClef (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ATTLIST Publication PremierAuteur IDREF #REQUIRED>
<!ATTLIST Publication CodePublication %unique;>
<!ATTLIST Date Jour CDATA #IMPLIED>
<!ATTLIST Date Month CDATA #IMPLIED>
<!ATTLIST Date Annee CDATA #REQUIRED>
<!ATTLIST Auteur IdAuteur ID #REQUIRED>
<!ATTLIST Auteur Role (Principale|CoAuteur|Correspondant|Superviseur) #REQUIRED>

=== ERRAFI-IMRANE/XML-TPS/TPS/TP2/Exercice-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Publications SYSTEM "Exercice-1.dtd">
<Publications>
    <Publication CodePublication="P001" PremierAuteur="A001">
        <Titre>Hackathon</Titre>
        <Auteur IdAuteur="A001" Role="Principale">
            <Nom></Nom>
            <Prenom></Prenom>
            <Affiliation></Affiliation>
        </Auteur>
        <Auteur IdAuteur="A002" Role="CoAuteur">
            <Nom></Nom>
            <Prenom></Prenom>
            <Affiliation></Affiliation>
        </Auteur>
        <Auteur IdAuteur="A003" Role="Correspondant">
            <Nom></Nom>
            <Prenom></Prenom>
            <Affiliation></Affiliation>
        </Auteur>
        <Date Jour="17" Month="05" Annee="2025"/>
        <Type></Type>
    </Publication>
    <Publication CodePublication="P002" PremierAuteur="A004">
        <Titre>Hackathon</Titre>
        <Auteur IdAuteur="A004" Role="Principale">
            <Nom></Nom>
            <Prenom></Prenom>
            <Affiliation></Affiliation>
        </Auteur>
        <Auteur IdAuteur="A005" Role="CoAuteur">
            <Nom></Nom>
            <Prenom></Prenom>
            <Affiliation></Affiliation>
        </Auteur>
        <Auteur IdAuteur="A006" Role="Correspondant">
            <Nom></Nom>
            <Prenom></Prenom>
            <Affiliation></Affiliation>
        </Auteur>
        <Date Jour="16" Month="05" Annee="2025"/>
        <Type></Type>
    </Publication>
</Publications>
